### ISSUE TITLE
Update Prices of wishlist everytime its opened

### ISSUE THREAD

**Issue by aadithya-naresh** [SE23-Team44/slash#15]
1. Update Prices by scraping the link in the backend.
2. Update the CSV and changed prices.
3. Add functions to scrape URL and get values for the following websites:
                1. Target
                2. BestBuy
                3. Amazon
                4. Walmart
                5. Google
                6. Ebay

**Comment by Sharatn7** [comment]
The backend scraping code has been executed on the wishlist items, successfully updating the prices.
