### ISSUE TITLE
 Liking Product Causes Page Scroll and Icon Display Issue

### ISSUE THREAD

**Issue by Sharatn7** [SE23-Team44/slash#20]
## Issue Description:
When attempting to like a product on the result page, there is a bug where the page scrolls to the top, and the heart icon of the liked product does not turn red. Despite this visual discrepancy, the product is successfully liked in the backend.

## Steps to Reproduce:

* Navigate to the result page of the application.
* Scroll down to view multiple products.
* Click on the heart icon of any product to like it.

## Expected Behavior:

The heart icon should turn red immediately upon clicking, indicating that the product has been liked.
There should be no abrupt scrolling to the top of the page.

**Comment by dhirajv2000** [comment]
I have fixed the issue that is causing the abrupt scrolling.
